### ISSUE TITLE
FundamentalData doesn't work with BSE data

### ISSUE THREAD

**Issue by miralchevli** [RomelTorres/alpha_vantage#308]
```
from alpha_vantage.fundamentaldata import FundamentalData
fd = FundamentalData(API_Key, output_format="pandas")

data1 = fd.get_income_statement_annual('TCS.BSE')
```

It gives an error like:
```
Traceback (most recent call last):
  File "D:\Stock\alpha_vantage\miral.py", line 12, in <module>
    data1 = fd.get_income_statement_annual('TCS.BSE')
  File "D:\Stock\alpha_vantage\alpha_vantage\alphavantage.py", line 218, in _format_wrapper
    call_response, data_key, meta_data_key = func(
  File "D:\Stock\alpha_vantage\alpha_vantage\alphavantage.py", line 160, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "D:\Stock\alpha_vantage\alpha_vantage\alphavantage.py", line 356, in _handle_api_call
    raise ValueError(
ValueError: Error getting data from the api, no return was given.
Process finished with exit code 1
```
It works with other symbols

**Comment by AlphaVantageSupport** [comment]
Hi @miralchevli, please kindly direct feature-specific questions to support@alphavantage.co. Thanks!
