### ISSUE TITLE
Crash on incorrect api key

### ISSUE THREAD

**Issue by jwallden** [RomelTorres/alpha_vantage#7]
When I gave it the wrong api key seems to crash:

Traceback (most recent call last):
File "av.py", line 4, in 
data, meta_data = ts.get_daily('STO:SAAB-B', outputsize='compact')
File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 152, in _format_wrapper
json_response, data_key, meta_data_key = func(self, *args, **kwargs)
File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 138, in _call_wrapper
return self._handle_api_call(url), data_key, meta_data_key
File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 76, in _retry_wrapper
raise ValueError(err)
UnboundLocalError: local variable 'err' referenced before assignment

**Comment by RomelTorres** [comment]
It only happens in python 3.5, in python 2.7 I get
```
>>> from alpha_vantage.timeseries import TimeSeries
>>> ts = TimeSeries(key='WRON')
>>> data, meta_data = ts.get_daily('STO:SAAB-B', outputsize='compact')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "alpha_vantage/alphavantage.py", line 152, in _format_wrapper
    json_response, data_key, meta_data_key = func(self, *args, **kwargs)
  File "alpha_vantage/alphavantage.py", line 138, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "alpha_vantage/alphavantage.py", line 76, in _retry_wrapper
    raise ValueError(err)
ValueError: ('ERROR getting data form api', 'Please make sure your API key is valid. Alternatively, claim your free API key on (http://www.alphavantage.co/support/#api-key). It should take less than 20 seconds, and is free permanently.')
```
Nevertheless I will also give it a try to fix it, thanks for your help.

Romel
