### ISSUE TITLE
alpha_vantage creates error

### ISSUE THREAD

**Issue by amadeus22** [RomelTorres/alpha_vantage#72]
#source: https://quantdare.com/forecasting-sp-500-using-machine-learning/

from alpha_vantage.timeseries import TimeSeries
import pandas as pd
print('Pandas_Version: ' + pd.__version__)
symbol = 'GOOGL'

ts = TimeSeries(key='_my_key_', output_format='pandas')
close = ts.get_daily(symbol=symbol, outputsize='full')[0]['close']   # compact/full
direction = (close > close.shift()).astype(int)
target = direction.shift(-1).fillna(0).astype(int)
target.name = 'target'

_____________________________________________________________________________________________________

results in error:

Pandas_Version: 0.23.0
Traceback (most recent call last):

  File "<ipython-input-23-c6eeea939d68>", line 1, in <module>
    runfile('F:/Eigene Dokumente_C/Documents/AI/Deep_Learning/test_stock_predictor.py', wdir='F:/Eigene Dokumente_C/Documents/AI/Deep_Learning')

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/Eigene Dokumente_C/Documents/AI/Deep_Learning/test_stock_predictor.py", line 16, in <module>
    close = ts.get_daily(symbol=symbol, outputsize='full')[0]['close']   # compact/full

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2685, in __getitem__
    return self._getitem_column(key)

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2692, in _getitem_column
    return self._get_item_cache(key)

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2486, in _get_item_cache
    values = self._data.get(item)

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)

  File "C:\Users\Ackermann\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3065, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))

  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'close'

**Comment by RomelTorres** [comment]
Hi, the error is that they key is not valid. We use the original Key from the alpha vantage API when building the panda dataframe. At the very beginning I use to strip down the keys from number and stuff, but I rather provide the data exactly as AV intended. Check the KEYS of the dataframes/rename them to get the behaviour you want.

BR Romel

**Comment by amadeus22** [comment]
Hola Romel.
thank you for your answer. I use a valid key provided by you. I just changed it here to: key='my_key' not to shw my key provided by you.
so it looks like: ts = TimeSeries(key='4BTFICZGTPWZRRQS', output_format='pandas')
If it what you mentioned it anyhow produces the error I mentioned before. I thought it might be a incompatbility problem with the newest Panda Version (here: 0.23.0) thats's the reason why I printed it out. It would be kind if you could show in it again. 

Muchos saludos desde Alemania

**Comment by RomelTorres** [comment]
Hey @amadeus22. I meant the keys in the panda dataframes. It is not 'close' but it should be something like '4. close'. (I edited your key out from the previous comment. Do  for example `print(ts.head(5))` to see the index column names Or check the json produced by the Alpha Vantage API on their website. I do not have any connection to the API providers, I just did the python wrapper. 

Saludos desde Alemania tambien.
Romel

**Comment by amadeus22** [comment]
Hi Romel,

thank you for your fast response. The solution is as follows:

from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
import pandas as pd
import matplotlib.pyplot as plt

print('Pandas Version: ' + pd.__version__)
#print('alpha_vantage Version: ' + alpha_vantage.__version__)

symbol = 'GOOGL'

# Technical Indicators
ti = TechIndicators(key='4BTFICZGTPWZRRQS', output_format='pandas')
sma, _ = ti.get_sma(symbol=symbol, interval='daily')
wma, _ = ti.get_wma(symbol='SPX', interval='daily')
ema, _ = ti.get_ema(symbol=symbol, interval='daily')
macd, _ = ti.get_macd(symbol=symbol, interval='daily')
stoch, _ = ti.get_stoch(symbol=symbol, interval='daily')
rsi, _ = ti.get_rsi(symbol=symbol, interval='daily')
adx, _ = ti.get_adx(symbol=symbol, interval='daily')
cci, _ = ti.get_cci(symbol=symbol, interval='daily')
aroon, _ = ti.get_aroon(symbol=symbol, interval='daily')
bbands, _ = ti.get_bbands(symbol='SPX', interval='daily')
ad, _ = ti.get_ad(symbol='SPX', interval='daily')
obv, _ = ti.get_obv(symbol='SPX', interval='daily')
mom, _ = ti.get_mom(symbol='SPX', interval='daily')
willr, _ = ti.get_willr(symbol='SPX', interval='daily')
tech_ind = pd.concat([sma, ema, macd, stoch, rsi, adx, cci, aroon, bbands, ad, obv, wma, mom, willr], axis=1)

ts = TimeSeries(key='4BTFICZGTPWZRRQS', output_format='pandas')
close = ts.get_daily(symbol=symbol, outputsize='full')[0]['4. close']
direction = (close > close.shift()).astype(int)
target = direction.shift(-1).fillna(0).astype(int)
target.name = 'target'

data = pd.concat([tech_ind, close, target], axis=1)

symbol = 'GOOGL'  # Google
print(data.tail(4))
data.describe()
ax = data['4. close'].plot(figsize=(9, 5))
ax.set_ylabel("Price ($)")
ax.set_xlabel("Time")
plt.show()

result is:

  willr, _ = ti.get_willr(symbol='SPX', interval='daily')
                  SMA        EMA  MACD_Signal   ...      WILLR  4. close  target
2018-05-18  1059.9595  1069.3743       6.2150   ...   -19.7519   1069.64     1.0
2018-05-21  1060.4695  1070.7681       6.7198   ...    -6.1636   1084.01     1.0
2018-05-22        NaN        NaN          NaN   ...   -12.0580       NaN     NaN
2018-05-23  1063.6355  1072.2150       7.1363   ...    -6.0628   1085.96     0.0

**Comment by RomelTorres** [comment]
Ok, Maybe I can make that work (getting the version) for the next version @amadeus22 

Saludos
Romel
